# Base de données de développement
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_dev?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=0000

# Hibernate : recréer la structure de la BDD proprement (à remettre sur "update" après !)
spring.jpa.hibernate.ddl-auto=update

# Afficher et formater les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true